config/routes.rb
Rails.application.routes.draw do
  
  resources :users

  resources :orders

  resources :products 

  resources :variants

  resources :categories do
    resources :subcategories, controller: 'categories/subcategories'
  end
  
  root 'products#index'

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product_categories
    has_many :products, through: :product_categories
    belongs_to :source_category, optional: true, inverse_of: :subcategories, class_name: 'Category', foreign_key: 'subcategory_id'
    has_many :subcategories, inverse_of: :source_category, class_name: 'Category', foreign_key: 'subcategory_id', dependent: :destroy
    validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy subcategory]

  def subcategories
    @categories = Category.all
    subcategory = Category.new(subcategory_id: @category.id)
    if subcategory.save
      redirect_to categories_path, notice: 'Subcategory was successfully created'
    else
      redirect_to categories_path, alert: "Can't save subcategory"
    end
  end

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @category = Category.where(id: params[:id])
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    @categories = Category.all
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :subcategory_id, :subcategory_name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category ID</th>
      <th>Category</th>
      <th>Subcategories</th>
      <th>Add New Subcategory</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
      <td><%= category.id %></td>
      <td><%= category.name %></td>
      <td><%= category.subcategory_name %></td>
      <td><%= link_to 'New Subcategory', new_category_subcategory_path(category) %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Category', new_category_path %>
<%= link_to 'New Product', new_product_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/subcategory.html.erb
<div class="field">
    <%= f.label :category %> 
    <select name="category[category_id]">
        <%= @categories.each do |category| %>
            <option value="<%= category.id %>">
            <%= category.name %>
            </option> 
        <% end %> 
    </select>
</div>

<%= form_with(model: category, local: true) do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
        <ul>
          <% category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
        <%= form.label :subcategory %>
        <%= form.text_field :subcategory_name %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>