config/routes.rb
Rails.application.routes.draw do
  
  resources :users

  resources :orders

  resources :products 

  resources :variants

  resources :categories do
    resources :subcategories, controller: 'categories/subcategories'
  end
  
  root 'products#index'

end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_categories
    has_many :categories, through: :product_categories
    has_many :variants, inverse_of: :product
    accepts_nested_attributes_for :variants, reject_if: :all_blank, allow_destroy: true

    def variant_size
        variants.pluck(:size)
    end

    def variant_color
        variants.pluck(:color)
    end

    def variant_stock
        variants.pluck(:stock)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, {category_ids: []}, variants_attributes: [:id, :size, :color, :stock, :product_id, :_destroy])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <p>Variants</p>
    <div id="products">
      <%= form.fields_for :variants do |variants_form| %>
        <%= render 'variant_fields', :f => variants_form %>
      <% end %>
    <div class='links'>
      <%= link_to_add_association 'Add variant', form, :variants %>
    </div>
  </div>
  
  <br>

  <div class="field">
    <%= form.label :categories %>
      <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
        <%= b.label class:"label-checkbox" do%>
          <%=b.check_box + b.text%>
        <%end%>
      <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_variant_fields.html.erb
<br>
<div class='nested-fields'>
    <div class="field">
        <%= f.label :size %>
        <%= f.text_field :size %>
    </div>
    <div class="field">
        <%= f.label :color %>
        <%= f.text_field :color %>
    </div>

    <div class="field">
        <%= f.label :stock %>
        <%= f.number_field :stock %>
    </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Catalogue</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
      <% if product.variant_stock.sum > 0 %>
        <td><%= product.name %></td>
        <td><%= product.variant_color.first %></td>
        <td><%= link_to 'View product', product %></td>
      <% end %>
        </tr>
    <% end %>
    <td><%= link_to 'New product',  new_product_path %></td>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>
<%= link_to 'Category', categories_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.variant_size %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.variant_color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.variant_stock %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>